x-app-common:
  &app-common
  image: cinebooker:local
  volumes:
    - ".:/cinebooker-dir"
  env_file:
    - .env

services:
  app:
    << : *app-common
    container_name: cinebooker__app
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.local
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cinebooker__network
    command: 'runserver.sh'

  db:
    << : *app-common
    image: postgres:18
    container_name: cinebooker__db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - cinebooker__network

  redis:
    container_name: cinebooker__redis
    image: redis:8.4-alpine  # NOTE: redis cannot be updated until a new celery version is released
    env_file:
      - .env
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - cinebooker__network

  celery:
    << : *app-common
    container_name: cinebooker__celery
    command: 'celery.sh'
    depends_on:
      - app
    networks:
      - cinebooker__network
    healthcheck:
      test: ["CMD", "uv", "run", "celery", "-A", "app.celery.celery", "status"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  flower:
    << : *app-common
    image: mher/flower:latest
    container_name: cinebooker__flower
    depends_on:
      celery:
        condition: service_healthy
    ports:
      - "5555:5555"
    networks:
      - cinebooker__network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  mailpit:
    image: axllent/mailpit
    container_name: cinebooker__mailpit
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port for Mailpit
    networks:
      - cinebooker__network

volumes:
  postgres_data:
    driver: local

networks:
  cinebooker__network:
    driver: bridge
